package FPAD::Writer;

use strict;
use warnings;

sub new {
    my ($class, %args) = @_;
    return bless {
        logger => $args{logger},
        parser => $args{parser},
    }, $class;
}

# --- 生成 Innovus 格式的 IO Constraint (_chip.const) ---
sub generate_innovus_io {
    my ($self, $filename) = @_;
    $self->{logger}->info("Generating Innovus IO Constraint: $filename");

    my $data = $self->{parser}->{data};
    my %sides;
    
    # 根據 LOCATION 分組
    foreach my $row (@$data) {
        my $pname = $row->{PIN_NAME};
        next if uc($pname) eq 'NC'; # NC 不在 APR 佈局中佔位
        
        # 使用從 Verilog 抓取到的真正實體名稱
        my $inst_name = $row->{INST_NAME};
        
        push @{$sides{uc($row->{LOCATION})}}, $inst_name;
    }

    open my $fh, '>', $filename or $self->{logger}->fatal("Cannot write to $filename: $!");
    
    print $fh "# Innovus IO Assignment File\n";
    print $fh "# Generated by FPAD_ASSIGN\n";
    print $fh "Version: 2\n\n";

    # 定義四邊映射
    my %map = ('L' => 'left', 'B' => 'bottom', 'R' => 'right', 'T' => 'top');

    foreach my $s (qw(L B R T)) {
        my $side_name = $map{$s};
        print $fh "$side_name:\n";
        if ($sides{$s}) {
            foreach my $inst (@{$sides{$s}}) {
                print $fh "    (inst name=\"$inst\")\n";
            }
        }
        print $fh "\n";
    }

    close $fh;
    $self->{logger}->info("Innovus IO file saved.");
}

1;
