# lib/fpad_py/writer.py

import os

class Writer:
    def __init__(self, logger, parser):
        self.logger = logger
        self.parser = parser

    def generate_innovus_io(self, filename):
        self.logger.info(f"Generating Innovus IO Constraint: {filename}")

        data = self.parser.data
        sides = {'L': [], 'B': [], 'R': [], 'T': []}
        
        # Group by LOCATION
        for row in data:
            pname = row['PIN_NAME']
            if pname.upper() == 'NC':
                continue
            
            inst_name = row['INST_NAME']
            location = row['LOCATION'].upper()
            if location in sides:
                sides[location].append(inst_name)

        try:
            with open(filename, 'w') as f:
                f.write("# Innovus IO Assignment File\n")
                f.write("# Generated by FPAD_ASSIGN (Python)\n")
                f.write("Version: 2\n\n")

                side_map = {'L': 'left', 'B': 'bottom', 'R': 'right', 'T': 'top'}

                for s in ['L', 'B', 'R', 'T']:
                    side_name = side_map[s]
                    f.write(f"{side_name}:\n")
                    for inst in sides[s]:
                        f.write(f"    (inst name=\"{inst}\" spacing=0 offset=0 place_status=placed)\n")
                    f.write("\n")

            self.logger.info("Innovus IO file saved.")
        except Exception as e:
            self.logger.error(f"Failed to write Innovus IO file: {e}")

    def generate_completed_list(self, filename):
        self.logger.info(f"Generating completed Pin List: {filename}")
        
        try:
            with open(filename, 'w') as f:
                # Write header
                for key, val in self.parser.header.items():
                    f.write(f"{key:<20} : {val}\n")
                f.write("\n")
                
                # Write table header
                header_str = f"{'PIN_NUM':<10} {'DIE_PAD_NUM':<12} {'PIN_NAME':<15} {'IO_CELL_NAME':<20} {'LOCATION':<10} {'DIR':<5} {'LOAD':<5} {'SLEW':<5} {'SSO':<5}"
                f.write(header_str + "\n")
                f.write("-" * len(header_str) + "\n")
                
                # Write data rows
                for r in self.parser.data:
                    row_str = f"{r['PIN_NUM']:<10} {r['DIE_PAD_NUM']:<12} {r['PIN_NAME']:<15} {r['IO_CELL_NAME']:<20} {r['LOCATION']:<10} {r['DIRECTION']:<5} {r['LOAD']:<5} {r['SLEW']:<5} {r['SSO']:<5}"
                    f.write(row_str + "\n")
                    
            self.logger.info("Completed Pin List saved.")
        except Exception as e:
            self.logger.error(f"Failed to write completed Pin List: {e}")
