#!/bin/bash

# 取得腳本所在的絕對路徑
SELF_PATH=$(cd "$(dirname "$0")"; pwd)

# 設定 Perl 搜尋路徑：優先搜尋封裝內的 lib 和 extlib
export PERL5LIB="$SELF_PATH/lib:$SELF_PATH/extlib:$PERL5LIB"

# 執行主程式，並傳遞所有參數
perl "$SELF_PATH/bin/fpad_assign.pl" "$@"
